name: empower_ability
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  avatar_glow: ^3.0.1
  flutter:
    sdk: flutter
  flutter_tts: ^3.8.5
  highlight_text: ^1.7.0
  speech_to_text: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/icons/
